import "./globals.css";
import { Hachi_Maru_Pop, Rampart_One } from "next/font/google";

const HachiMaruPopFont = Hachi_Maru_Pop({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-HachiMaruPop",
});
const RampartOneFont = Rampart_One({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-RampartOne",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body
        className={`${HachiMaruPopFont.variable} ${RampartOneFont.variable} font-HachiMaruPop`}
      >
        {children}
      </body>
    </html>
  );
}
