import "./globals.css";
import { Hachi_Maru_Pop } from "next/font/google";

const HachiMaruPopFont = Hachi_Maru_Pop({ weight: "400", subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body className={HachiMaruPopFont.className}>{children}</body>
    </html>
  );
}